### PR TITLE
adjust some color

### PR DESCRIPTION
**Pull request by rocascent**

### CODE REVIEW

**Comment by johnyenter-briars** [comment]
@Gn3po4g  - looks great!

You just bump the version num to `0.13.0` in [source.extension.vsixmanifest](https://github.com/johnyenter-briars/gruvbox-material-vs/blob/7dd9b95179a9f8fe15ee8c15391cfafc57f63bf5/gruvbox-material-vs/source.extension.vsixmanifest#L4)?

And then just ping me when you're ready for this to be merged, and I will merge / publish the extension.

**Comment by rocascent** [comment]
i think you can merge now

**Comment by johnyenter-briars** [comment]
> i think you can merge now

Can you see my comment from above? Can you please bump the version num in the visxmanifest? That needs to incremented in order to publish an update on the vs marketplace.

**Comment by rocascent** [comment]
> > i think you can merge now
> 
> Can you see my comment from above? Can you please bump the version num in the visxmanifest? That needs to incremented in order to publish an update on the vs marketplace.

sorry I forgot, is it okay now.

**Comment by johnyenter-briars** [comment]
> > > i think you can merge now
> > 
> > 
> > Can you see my comment from above? Can you please bump the version num in the visxmanifest? That needs to incremented in order to publish an update on the vs marketplace.
> 
> sorry I forgot, is it okay now.

Looks great - thank you for your contribution! I will publish the extension shortly! You should see an update in the visual studio extension store soon. 

Edit: 

VS Extension store is down until the azure degradation is resolved https://azure.status.microsoft/en-us/status

**Pull request merged**
