### PR TITLE
Add `StickyScroll Background`

### PR DESCRIPTION
**Pull request by rocascent**
closing #22

### CODE REVIEW

**Comment by rocascent** [comment]
@johnyenter-briars please check.
And if you don't mind i want to open a pr to adjust the project files.

**Comment by rocascent** [comment]
image
Or use `ToolWindowBorder` to seperate?

**Comment by johnyenter-briars** [comment]
@Gn3po4g I will run a local build to check today 👍

I'm fine with you re-arranging the proj files. You can just include those changes in this PR : )

**Comment by johnyenter-briars** [comment]
@Gn3po4g  - this looks great! Thank you 

Unfortunately - I'm away from my home lab right now.

I'll push this to the vs marketplace on monday.

**Pull request merged**
